#!/usr/bin/env bash
# neovim_themegen.sh — writes the LazyVim plugin spec for yukazakiri/inir.nvim.
# The plugin itself handles all colour fetching, highlights, and live reload.
#
# Usage: neovim_themegen.sh <palette.json> <terminal.json> <plugin_dir>
set -euo pipefail

PALETTE_FILE="${1:?Usage: $0 <palette.json> <terminal.json> <plugin_dir>}"
TERMINAL_FILE="${2:?}"
NEOVIM_PLUGIN_DIR="${3:?}"

NEOVIM_CONFIG_DIR="$(dirname "$(dirname "$NEOVIM_PLUGIN_DIR")")"

# Write file only if changed
write_if_changed() {
  local target="$1" tmp="${1}.tmp"
  cat > "$tmp"
  if [[ -f "$target" ]] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    printf '[neovim_themegen] %s updated\n' "$(basename "$target")"
  fi
}

mkdir -p "$NEOVIM_PLUGIN_DIR"
write_if_changed "$NEOVIM_PLUGIN_DIR/neovim.lua" <<'PLUGEOF'
-- neovim.lua — auto-generated by iNiR. Use 99-inir-user.lua for overrides.
--
-- Material You palettes are intentionally low-saturation, which reads as
-- "washed out" in code. The hooks below saturate the wallpaper palette so
-- syntax pops, make errors loud, and give the selection a strong, visible
-- block — all derived from the live palette so it still tracks the wallpaper.

local function clamp(x) return math.max(0, math.min(1, x)) end

local function is_hex(v)
  return type(v) == "string" and v:match("^#%x%x%x%x%x%x$") ~= nil
end

local function hex_to_rgb(hex)
  hex = hex:gsub("#", "")
  return tonumber(hex:sub(1, 2), 16) / 255,
         tonumber(hex:sub(3, 4), 16) / 255,
         tonumber(hex:sub(5, 6), 16) / 255
end

local function rgb_to_hex(r, g, b)
  return string.format("#%02x%02x%02x",
    math.floor(clamp(r) * 255 + 0.5),
    math.floor(clamp(g) * 255 + 0.5),
    math.floor(clamp(b) * 255 + 0.5))
end

local function rgb_to_hsl(r, g, b)
  local mx, mn = math.max(r, g, b), math.min(r, g, b)
  local h, s, l = 0, 0, (mx + mn) / 2
  local d = mx - mn
  if d ~= 0 then
    s = l > 0.5 and d / (2 - mx - mn) or d / (mx + mn)
    if mx == r then h = (g - b) / d + (g < b and 6 or 0)
    elseif mx == g then h = (b - r) / d + 2
    else h = (r - g) / d + 4 end
    h = h / 6
  end
  return h, s, l
end

local function hue_to_rgb(p, q, t)
  if t < 0 then t = t + 1 end
  if t > 1 then t = t - 1 end
  if t < 1 / 6 then return p + (q - p) * 6 * t end
  if t < 1 / 2 then return q end
  if t < 2 / 3 then return p + (q - p) * (2 / 3 - t) * 6 end
  return p
end

local function hsl_to_rgb(h, s, l)
  if s == 0 then return l, l, l end
  local q = l < 0.5 and l * (1 + s) or l + s - l * s
  local p = 2 * l - q
  return hue_to_rgb(p, q, h + 1 / 3), hue_to_rgb(p, q, h), hue_to_rgb(p, q, h - 1 / 3)
end

-- Saturate a swatch; only lighten mid/high-lightness tones so backgrounds
-- stay dark. Neutral grays (s == 0) are left untinted.
local function vivify(hex, sat_mul, light_add)
  if not is_hex(hex) then return hex end
  local h, s, l = rgb_to_hsl(hex_to_rgb(hex))
  if s > 0 then s = clamp(s * sat_mul) end
  if l > 0.22 then l = clamp(l + light_add) end
  return rgb_to_hex(hsl_to_rgb(h, s, l))
end

-- Linear blend between two hex colors (t = 0 -> a, t = 1 -> b).
local function mix(a, b, t)
  if not (is_hex(a) and is_hex(b)) then return a end
  local ar, ag, ab = hex_to_rgb(a)
  local br, bg, bb = hex_to_rgb(b)
  return rgb_to_hex(ar + (br - ar) * t, ag + (bg - ag) * t, ab + (bb - ab) * t)
end

return {
  {
    "yukazakiri/inir.nvim",
    priority = 1000,
    opts = {
      on_colors = function(colors)
        -- Gently lift saturation for code readability. The palette is already
        -- balanced upstream (accent chroma floor, harmonized tertiary), so
        -- this is a light touch: backgrounds barely move, syntax swatches get
        -- a moderate boost to read clearly against dark surfaces.
        for key, value in pairs(colors) do
          if is_hex(value) then
            local lower = tostring(key):lower()
            local is_bg = lower:find("bg") or lower:find("background")
                       or lower:find("base") or lower:find("dark")
            colors[key] = vivify(value, is_bg and 1.08 or 1.3, is_bg and 0 or 0.06)
          end
        end
      end,
      on_highlights = function(hl, c)
        local fg = c.fg or "#e6e6e6"
        local bg = c.bg or c.background or "#11131a"
        local accent = c.accent or c.blue or "#7aa2f7"
        local err = "#ff4d4d"

        -- Very visible selection: a strong accent block, syntax fg preserved.
        local sel_bg = mix(accent, bg, 0.5)
        hl.Visual = { bg = sel_bg, bold = true }
        hl.VisualNOS = { bg = sel_bg, bold = true }

        -- Searches stand out too.
        hl.Search = { bg = mix(accent, bg, 0.35), fg = fg, bold = true }
        hl.IncSearch = { bg = err, fg = bg, bold = true }
        hl.CurSearch = { bg = err, fg = bg, bold = true }

        -- Errors scream.
        hl.Error = { fg = err, bold = true }
        hl.ErrorMsg = { fg = err, bold = true }
        hl.DiagnosticError = { fg = err, bold = true }
        hl.DiagnosticFloatingError = { fg = err, bold = true }
        hl.DiagnosticSignError = { fg = err, bold = true }
        hl.DiagnosticVirtualTextError = { fg = err, bg = mix(err, bg, 0.82), bold = true }
        hl.DiagnosticUnderlineError = { sp = err, undercurl = true }
        hl["@text.danger"] = { fg = err, bold = true }
        hl["@comment.error"] = { fg = err, bold = true }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "inir",
    },
  },
}
PLUGEOF

# Clean up stale files from previous versions
for stale in \
  "$NEOVIM_PLUGIN_DIR/inir-colorscheme.lua" \
  "$NEOVIM_PLUGIN_DIR/inir_theme.lua" \
  "$NEOVIM_CONFIG_DIR/colors/inir.lua"
do
  if [[ -f "$stale" ]]; then
    rm -f "$stale"
    printf '[neovim_themegen] removed stale: %s\n' "$(basename "$stale")"
  fi
done
