// Liquid glass edges — analytic version of the five stacked gradient rectangles
// in LiquidGlassEdges.qml. Everything is derived from a rounded-box SDF, so the
// rim brightness follows the surface normal and the highlight wraps the rounded
// corners instead of running as a straight line across the top.
//
// There is no shader build step in this repo: the .qsb is generated by hand and
// committed next to this file, exactly like FluidRipple.frag. After editing:
//
//   /usr/lib/qt6/bin/qsb --glsl "100 es,120,150" --hlsl 50 --msl 12 \
//     -o modules/common/widgets/LiquidGlass.qsb modules/common/widgets/LiquidGlass.frag

#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

// qt_Matrix and qt_Opacity must stay first and in this order: the built-in
// vertex shader declares its own block at binding 0 with exactly that prefix,
// and both stages share one uniform buffer.
//
// Every other member needs a QML property of the same name on the ShaderEffect,
// or Qt logs "does not have a matching property" and the value reads as zero.
//
// Colours arrive premultiplied (rgb = colour * a), which is what the
// accumulation below assumes. A disabled sub-effect passes "transparent",
// i.e. vec4(0), and drops out of the sum for free — hence no enable flags.
layout(std140, binding = 0) uniform buf {
    mat4  qt_Matrix;
    float qt_Opacity;
    float glassRadius;    // px — corner radius of the surface
    float glassBevel;     // px — how far the thickness falloff reaches inward
    float glassRim;       // px — hairline width
    float glassDisp;      // 0..1 — chromatic split of the rim
    vec2  glassSize;      // px
    vec2  glassLight;     // screen space direction, +y down
    vec4  colEdge;
    vec4  colShade;
    vec4  colSpecular;
    vec4  colSheen;
} ubuf;

// Signed distance to a rounded box centred on the origin. Negative inside.
float sdRoundBox(vec2 p, vec2 b, float r) {
    vec2 q = abs(p) - b + r;
    return min(max(q.x, q.y), 0.0) + length(max(q, vec2(0.0))) - r;
}

// 1 on the boundary, falling to 0 at `w` pixels inside.
float rimProfile(float d, float w, float aa) {
    return 1.0 - smoothstep(0.0, max(w, aa), -d);
}

void main() {
    vec2 halfSize = ubuf.glassSize * 0.5;
    vec2 p = qt_TexCoord0 * ubuf.glassSize - halfSize;
    float r = clamp(ubuf.glassRadius, 0.0, min(halfSize.x, halfSize.y));
    float d = sdRoundBox(p, halfSize, r);

    // One device pixel in item units, so every edge stays a pixel wide at any
    // scale or device pixel ratio.
    float aa = max(fwidth(d), 0.0001);

    // Analytic mask — the effect clips itself to the rounded body instead of
    // relying on the parent's clip or OpacityMask.
    float mask = clamp(0.5 - d / aa, 0.0, 1.0);

    // Outward normal from the SDF gradient, by central differences over a fixed
    // 1px epsilon so it stays stable through the corners. This is what makes the
    // highlight wrap the rounding.
    const float e = 1.0;
    vec2 grad = vec2(
        sdRoundBox(p + vec2(e, 0.0), halfSize, r) - sdRoundBox(p - vec2(e, 0.0), halfSize, r),
        sdRoundBox(p + vec2(0.0, e), halfSize, r) - sdRoundBox(p - vec2(0.0, e), halfSize, r));
    vec2 n = normalize(grad + vec2(1e-6));
    vec2 L = normalize(ubuf.glassLight + vec2(1e-6));

    float lambert = dot(n, L);
    float lit  = max(lambert, 0.0);
    float dark = max(-lambert, 0.0);

    // Inner bevel — the glass reading as something with thickness.
    float bevel = rimProfile(d, ubuf.glassBevel, aa);
    bevel *= bevel;

    // Hairline rim, split per channel so the edge disperses like real glass.
    float dw = ubuf.glassDisp * 0.5;
    vec3 rimRGB = vec3(
        rimProfile(d, ubuf.glassRim * (1.0 + dw), aa),
        rimProfile(d, ubuf.glassRim, aa),
        rimProfile(d, max(ubuf.glassRim * (1.0 - dw), 0.35), aa));
    float rimA = rimRGB.g;

    // The floor keeps a defined edge all the way round; the rest follows light.
    // Weighted well above 1 on the lit side so the rim reads as light actually
    // caught in the bevel rather than a hairline drawn on top.
    float hi = 0.5 + 1.5 * lit;

    vec3  rgb = vec3(0.0);
    float a   = 0.0;

    // Sheen — top-down gradient, matching the old 0.0 -> 0.35 gradient stops.
    float sheen = 1.0 - smoothstep(0.0, 0.35, qt_TexCoord0.y);
    rgb += ubuf.colSheen.rgb * sheen;
    a   += ubuf.colSheen.a   * sheen;

    // Specular gleam — soft diagonal band. tan(18 deg) ~= 0.325, matching the
    // -18 degree rotation of the old gradient rectangle.
    float g = qt_TexCoord0.y + qt_TexCoord0.x * 0.325;
    float band = smoothstep(0.06, 0.34, g) * (1.0 - smoothstep(0.34, 0.78, g));
    rgb += ubuf.colSpecular.rgb * band;
    a   += ubuf.colSpecular.a   * band;

    // Edge highlight — hairline plus bevel, both weighted by the normal.
    float bevLit = bevel * 1.0 * lit;
    rgb += ubuf.colEdge.rgb * (rimRGB * hi + vec3(bevLit));
    a   += ubuf.colEdge.a   * (rimA   * hi + bevLit);

    // Edge shade — colShade is black, so its premultiplied rgb is 0 and only the
    // alpha term darkens what is behind. That is the correct "over" result.
    float shade = rimA * dark * 0.3 + bevel * 0.12 * dark;
    rgb += ubuf.colShade.rgb * shade;
    a   += ubuf.colShade.a   * shade;

    a   = clamp(a, 0.0, 1.0);
    rgb = min(rgb, vec3(a));

    float k = mask * ubuf.qt_Opacity;
    fragColor = vec4(rgb * k, a * k);
}
