// Liquid glass edges, refracting variant. Identical to LiquidGlass.frag plus a
// backdrop sampler: inside the bevel band the wallpaper is sampled with the UVs
// displaced along the surface normal, per channel, so the edge behaves like a
// real lens instead of a painted highlight.
//
// This is only used where a wallpaper texture actually exists (the panel already
// paints a blurred copy of it). With real transparency on there is nothing to
// bend — the compositor shows the real windows — so LiquidGlassEdges falls back
// to the sampler-less LiquidGlass.qsb. Never make the sampler conditional inside
// one shader: an unbound sampler2D gets a dummy texture and a warning.
//
// The sampled texture is the *sharp* wallpaper, not the blurred copy: an Item's
// texture provider exposes its pre-effect content, so `layer.effect: MultiEffect`
// output is not reachable without a second screen-sized FBO. That is also the
// better look — a real bevel shows a sharper, distorted image at the edge while
// the body stays frosted.
//
// There is no shader build step in this repo: the .qsb is generated by hand and
// committed next to this file. After editing:
//
//   /usr/lib/qt6/bin/qsb --glsl "100 es,120,150" --hlsl 50 --msl 12 \
//     -o modules/common/widgets/LiquidGlassRefract.qsb \
//        modules/common/widgets/LiquidGlassRefract.frag

#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(std140, binding = 0) uniform buf {
    mat4  qt_Matrix;
    float qt_Opacity;
    float glassRadius;    // px — corner radius of the surface
    float glassBevel;     // px — how far the thickness falloff reaches inward
    float glassRim;       // px — hairline width
    float glassDisp;      // 0..1 — chromatic split of the rim
    float glassRefract;   // px — maximum UV displacement at the edge
    vec2  glassSize;      // px
    vec2  glassLight;     // screen space direction, +y down
    vec4  colEdge;
    vec4  colShade;
    vec4  colSpecular;
    vec4  colSheen;
    vec4  glassMap;       // backdropUV = glassMap.xy + uv * glassMap.zw
} ubuf;

layout(binding = 1) uniform sampler2D backdrop;

// Signed distance to a rounded box centred on the origin. Negative inside.
float sdRoundBox(vec2 p, vec2 b, float r) {
    vec2 q = abs(p) - b + r;
    return min(max(q.x, q.y), 0.0) + length(max(q, vec2(0.0))) - r;
}

// 1 on the boundary, falling to 0 at `w` pixels inside.
float rimProfile(float d, float w, float aa) {
    return 1.0 - smoothstep(0.0, max(w, aa), -d);
}

// Push colour away from its luma. s = 1 is a no-op, > 1 saturates.
vec3 saturate3(vec3 c, float s) {
    float l = dot(c, vec3(0.2126, 0.7152, 0.0722));
    return max(mix(vec3(l), c, s), vec3(0.0));
}

void main() {
    vec2 halfSize = ubuf.glassSize * 0.5;
    vec2 p = qt_TexCoord0 * ubuf.glassSize - halfSize;
    float r = clamp(ubuf.glassRadius, 0.0, min(halfSize.x, halfSize.y));
    float d = sdRoundBox(p, halfSize, r);

    float aa = max(fwidth(d), 0.0001);
    float mask = clamp(0.5 - d / aa, 0.0, 1.0);

    const float e = 1.0;
    vec2 grad = vec2(
        sdRoundBox(p + vec2(e, 0.0), halfSize, r) - sdRoundBox(p - vec2(e, 0.0), halfSize, r),
        sdRoundBox(p + vec2(0.0, e), halfSize, r) - sdRoundBox(p - vec2(0.0, e), halfSize, r));
    vec2 n = normalize(grad + vec2(1e-6));
    vec2 L = normalize(ubuf.glassLight + vec2(1e-6));

    float lambert = dot(n, L);
    float lit  = max(lambert, 0.0);
    float dark = max(-lambert, 0.0);

    float bevel = rimProfile(d, ubuf.glassBevel, aa);
    bevel *= bevel;

    float dw = ubuf.glassDisp * 0.5;
    vec3 rimRGB = vec3(
        rimProfile(d, ubuf.glassRim * (1.0 + dw), aa),
        rimProfile(d, ubuf.glassRim, aa),
        rimProfile(d, max(ubuf.glassRim * (1.0 - dw), 0.35), aa));
    float rimA = rimRGB.g;

    // Kept close to 1 rather than spiking to 2 — the old range read as an
    // almost-opaque cap right at the boundary that then fell straight to the
    // body's flat alpha, i.e. a seam instead of one continuous material.
    float hi = 0.35 + 0.65 * lit;

    // ─── Refraction ───
    // Pull the sample inward along -n, strongest at the edge and fading with the
    // bevel. Scaling the mix by strength too means a strength of 0 is a true
    // no-op rather than an undisplaced (and therefore sharpening) copy.
    float strength = clamp(ubuf.glassRefract / 64.0, 0.0, 1.0);
    float refrW = bevel * strength;

    vec2 base = ubuf.glassMap.xy + qt_TexCoord0 * ubuf.glassMap.zw;
    vec2 push = (-n * ubuf.glassRefract * bevel) / ubuf.glassSize * ubuf.glassMap.zw;
    vec3 refr = vec3(
        texture(backdrop, base + push * (1.0 + dw)).r,
        texture(backdrop, base + push).g,
        texture(backdrop, base + push * (1.0 - dw)).b);
    // Saturation pump — the same move the SVG filter makes with
    // `feColorMatrix type="saturate"`. Displacing the image alone reads as a
    // smudge; the colour boost is what makes the edge look like thick glass.
    refr = saturate3(refr, 1.0 + 3.0 * strength);

    // The refracted backdrop is the base layer; the highlights accumulate over
    // it. Premultiplied, so rgb is already weighted by its own alpha.
    vec3  rgb = refr * refrW;
    float a   = refrW;

    // Sheen — ambient wash falling off along the light direction instead of
    // straight down, so the surface and the rim agree on where the light is.
    // The 0.72 falloff keeps mid-surface coverage equal to the old 0.55
    // vertical stop, just tilted.
    float along = dot(qt_TexCoord0, -L);
    float sheen = 1.0 - smoothstep(0.0, 0.72, along);
    rgb += ubuf.colSheen.rgb * sheen;
    a   += ubuf.colSheen.a   * sheen;

    float g = qt_TexCoord0.y + qt_TexCoord0.x * 0.325;
    float band = smoothstep(0.06, 0.34, g) * (1.0 - smoothstep(0.34, 0.78, g));
    rgb += ubuf.colSpecular.rgb * band;
    a   += ubuf.colSpecular.a   * band;

    // Weight cut to 0.6: at 1.0 it stacked with the hairline and the
    // refraction band above to make the rim read as near-opaque against the
    // body's actual base alpha.
    float bevLit = bevel * 0.6 * lit;
    rgb += ubuf.colEdge.rgb * (rimRGB * hi + vec3(bevLit));
    a   += ubuf.colEdge.a   * (rimA   * hi + bevLit);

    float shade = rimA * dark * 0.3 + bevel * 0.12 * dark;
    rgb += ubuf.colShade.rgb * shade;
    a   += ubuf.colShade.a   * shade;

    a   = clamp(a, 0.0, 1.0);
    rgb = min(rgb, vec3(a));

    float k = mask * ubuf.qt_Opacity;
    fragColor = vec4(rgb * k, a * k);
}
